select rtrim(RMFGR||RCOLOR||RPATT) as itemNumber,
       RDEL,
       RMFGR,
       RCOLOR,
       RPATT,
       RISHAD,
       RILOT#,
       RWARE#,
       RROLL#,
       RLOC1,
       RONHAN,
       RSCHED,
       RALLOC,
       RLASTC,
       RBASEC,
       RLRCTD,
       R#CUTS,
       RUM,
       RSHADE,
       RFILL1,
       RCODE@,
       RORIG,
       RHOLD
from rolls
where ronhan > 0
