WITH CombinedData AS (
    SELECT 'BWL' AS schemaName,
           RTRIM(CONCAT(item.imfgr, item.icolor, item.ipatt)) AS ITEMNUMBER,
           [IMFGR],
    [ICOLOR],
    [IPATT],
    [ISHADE],
    [ILOT#],
    [ICOLDE],
    [INAME],
    [INAME2],
    [IABC],
    [IDISCD],
    [ISITM#],
    [ICCTR],
    [IUNDER],
    [IUNDGL],
    [IMINCD],
    [IODAYS],
    [IPATH],
    [IFILL3],
    [IXTRCD],
    [IUMSUP],
    [IISOT#],
    [IIXREF],
    [IQBGRP],
    [IFRTCL],
    [IPRTUM],
    [IUMSAL],
    [ICLAST],
    [ICLAS1],
    [ICLAS2],
    [ICLAS3],
    [IPATDE],
    [ISPCL#],
    [IDELIV],
    [IPOL1],
    [IPOL2],
    [IPOL3],
    [IFIL2],
    [IMIN],
    [ITAX],
    [IQBMUL],
    [ILPODT],
    [ILRCTD],
    [ISEQ#],
    [IINIT],
    [IINVEN],
    [ICOMPO],
    [IPRCCD],
    [IPACCD],
    [ICSTCD],
    [IUM2],
    [IIM#1],
    [IIM#2],
    [IIM#3],
    [IIM#4],
    [IIM#5],
    [IIM#6],
    [IIM11@],
    [IIM12@],
    [IIM13@],
    [IIM14@],
    [IIM15@],
    [IIM16@],
    [IIM21@],
    [IIM22@],
    [IIM23@],
    [IIM24@],
    [IIM25@],
    [IIM26@],
    [IQTYLM],
    [IQTYLY],
    [IUMPRC],
    [IDFTGP],
    [ILIST],
    [IUNITS],
    [IUNITC],
    [ISUPP#],
    [IPRODL],
    [ICOMM1],
    [IWEARC],
    [IWIDTH],
    [IREMNA],
    [ICOMLV],
    [ILCHDT],
    [IFLAGS],
    [IDEL],
    [MFGR#],
    [MNAME],
    [LID],
    [LMFGR#],
    [LPROD#],
    [LNAME],
    [LUNITS],
    [SUPP#],
    [SNAME],
    [SPOL1],
    [SPOL2],
    [SPOL3],
    [UPACCD],
    [UM#@1],
    [UM#@2],
    [UM#@3],
    [UM#@4],
    [UM#@5],
    [UM#@6],
    [UM1@1],
    [UM1@2],
    [UM1@3],
    [UM1@4],
    [UM1@5],
    [UM1@6],
    [UM2@1],
    [UM2@2],
    [UM2@3],
    [UM2@4],
    [UM2@5],
    [UM2@6],
    [UDESC],
    [UFILL1],
    [UPRTIN],
    [ULCHDT],
    [UDEL],
    [$PRCCD],
    [$LIST#],
    [$ENDUS],
    [$UNITS],
    [$DESC],
           1 AS priority
    FROM dancik_bwl.item AS item
    LEFT JOIN dancik_bwl.mfgr AS mfgr ON imfgr = mfgr#
    LEFT JOIN dancik_bwl.prodline AS prodline ON imfgr = lmfgr# AND iprodl = lprod#
    LEFT JOIN dancik_bwl.supplier AS supplier ON isupp# = supp#
    LEFT JOIN dancik_bwl.package AS package ON ipaccd = upaccd
    LEFT JOIN dancik_bwl.price AS price ON iprccd = [$PRCCD] AND [$LIST#] = 'LP'
    WHERE idiscd = 0
      AND icompo IN ('S', 'R')
      AND iixref = ''

    UNION ALL

    SELECT 'WAN' AS schemaName,
           RTRIM(CONCAT(item.imfgr, item.icolor, item.ipatt)) AS ITEMNUMBER,
           [IMFGR],
    [ICOLOR],
    [IPATT],
    [ISHADE],
    [ILOT#],
    [ICOLDE],
    [INAME],
    [INAME2],
    [IABC],
    [IDISCD],
    [ISITM#],
    [ICCTR],
    [IUNDER],
    [IUNDGL],
    [IMINCD],
    [IODAYS],
    [IPATH],
    [IFILL3],
    [IXTRCD],
    [IUMSUP],
    [IISOT#],
    [IIXREF],
    [IQBGRP],
    [IFRTCL],
    [IPRTUM],
    [IUMSAL],
    [ICLAST],
    [ICLAS1],
    [ICLAS2],
    [ICLAS3],
    [IPATDE],
    [ISPCL#],
    [IDELIV],
    [IPOL1],
    [IPOL2],
    [IPOL3],
    [IFIL2],
    [IMIN],
    [ITAX],
    [IQBMUL],
    [ILPODT],
    [ILRCTD],
    [ISEQ#],
    [IINIT],
    [IINVEN],
    [ICOMPO],
    [IPRCCD],
    [IPACCD],
    [ICSTCD],
    [IUM2],
    [IIM#1],
    [IIM#2],
    [IIM#3],
    [IIM#4],
    [IIM#5],
    [IIM#6],
    [IIM11@],
    [IIM12@],
    [IIM13@],
    [IIM14@],
    [IIM15@],
    [IIM16@],
    [IIM21@],
    [IIM22@],
    [IIM23@],
    [IIM24@],
    [IIM25@],
    [IIM26@],
    [IQTYLM],
    [IQTYLY],
    [IUMPRC],
    [IDFTGP],
    [ILIST],
    [IUNITS],
    [IUNITC],
    [ISUPP#],
    [IPRODL],
    [ICOMM1],
    [IWEARC],
    [IWIDTH],
    [IREMNA],
    [ICOMLV],
    [ILCHDT],
    [IFLAGS],
    [IDEL],
    [MFGR#],
    [MNAME],
    [LID],
    [LMFGR#],
    [LPROD#],
    [LNAME],
    [LUNITS],
    [SUPP#],
    [SNAME],
    [SPOL1],
    [SPOL2],
    [SPOL3],
    [UPACCD],
    [UM#@1],
    [UM#@2],
    [UM#@3],
    [UM#@4],
    [UM#@5],
    [UM#@6],
    [UM1@1],
    [UM1@2],
    [UM1@3],
    [UM1@4],
    [UM1@5],
    [UM1@6],
    [UM2@1],
    [UM2@2],
    [UM2@3],
    [UM2@4],
    [UM2@5],
    [UM2@6],
    [UDESC],
    [UFILL1],
    [UPRTIN],
    [ULCHDT],
    [UDEL],
    [$PRCCD],
    [$LIST#],
    [$ENDUS],
    [$UNITS],
    [$DESC],
           2 AS priority
    FROM dancik_wan.item AS item
    LEFT JOIN dancik_wan.mfgr AS mfgr ON imfgr = mfgr#
    LEFT JOIN dancik_wan.prodline AS prodline ON imfgr = lmfgr# AND iprodl = lprod#
    LEFT JOIN dancik_wan.supplier AS supplier ON isupp# = supp#
    LEFT JOIN dancik_wan.package AS package ON ipaccd = upaccd
    LEFT JOIN dancik_wan.price AS price ON iprccd = [$PRCCD] AND [$LIST#] = 'LP'
    WHERE idiscd = 0
      AND icompo IN ('S', 'R')
      AND iixref = ''
),
Flags AS (
    SELECT ITEMNUMBER,
           MAX(CASE WHEN schemaName = 'BWL' THEN 1 ELSE 0 END) AS isBWL,
           MAX(CASE WHEN schemaName = 'WAN' THEN 1 ELSE 0 END) AS isWAN
    FROM CombinedData
    GROUP BY ITEMNUMBER
),
RankedData AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY ITEMNUMBER ORDER BY priority) AS rn
    FROM CombinedData
)
SELECT r.*,
       f.isBWL,
       f.isWAN
FROM RankedData r
INNER JOIN Flags f ON r.ITEMNUMBER = f.ITEMNUMBER
WHERE r.rn = 1
ORDER BY r.IMFGR, r.IPRODL, r.ICOLOR, r.IPATT;