with CombinedData as (
    select 'BWL' as schemaName,
           accountNumber
           ,[BCO#]
      ,[BACCT#] as BACCT
      ,[BSLMN#] as BSLMN
      ,[BNAME]
      ,[BADDR1]
      ,[BADDR2]
      ,[BCITY]
      ,[BSTATE]
      ,[BZIP1]
      ,[BZIP2]
      ,[BCTRY]
      ,[BCONTA]
      ,[BPHONB]
      ,[BPHONH]
      ,[BOPEND]
      ,[BLCHDT]
      ,[BDBA]
      ,[BGUAR]
      ,[BTERPC]
      ,[BTERDA]
      ,[BTERCD]
      ,[BBO]
      ,[BCRMGR]
      ,[BHOLDQ]
      ,[BHOLD]
      ,[BHCHG]
      ,[BOV120]
      ,[BCOUNT]
      ,[BWHERE]
      ,[BLANGU]
      ,[BSPCLP]
      ,[BPOWRK]
      ,[BBRAN#] as BBRAN
      ,[BINVWK]
      ,[BORDER]
      ,[BTRRT1]
      ,[BTRRT2]
      ,[BTRRT3]
      ,[BPRVBA]
      ,[BSLAST]
      ,[BS2YAG]
      ,[BBNK#1]
      ,[BBANK1]
      ,[FILLER]
      ,[BMSGCD]
      ,[BAR#] as BAR
      ,[BML]
      ,[BINT$] as BINT
      ,[BBNK#2] as BBNK2
      ,[BBANK2]
      ,[FILL1]
      ,[BSHIP#] as BSHIP
      ,[BWARE#] as BWARE
      ,[BCHAIN]
      ,[BINTPC]
      ,[FILL2]
      ,[BSS#] as BSS
      ,[BSTHIS]
      ,[BOPENA]
      ,[BOV15]
      ,[BOV30]
      ,[BOV45]
      ,[BOV60]
      ,[BOV90]
      ,[BMINYN]
      ,[BDELYN]
      ,[BOPENP]
      ,[BCLIMI]
      ,[BBALFW]
      ,[BBCOCD]
      ,[BCLAS2]
      ,[BCOPIE]
      ,[BCOMM1]
      ,[BCOMM2]
      ,[BLPAYD]
      ,[BLSALD]
      ,[BCLAS3]
      ,[BTAXST]
      ,[BTAXOT]
      ,[BFILL3]
      ,[BPREF]
      ,[BDEL]
    from dancik_bwl.billto

    union all

    select 'WAN' as schemaName,
           accountNumber
           ,[BCO#]
            ,[BACCT#] as BACCT
      ,[BSLMN#] as BSLMN
      ,[BNAME]
      ,[BADDR1]
      ,[BADDR2]
      ,[BCITY]
      ,[BSTATE]
      ,[BZIP1]
      ,[BZIP2]
      ,[BCTRY]
      ,[BCONTA]
      ,[BPHONB]
      ,[BPHONH]
      ,[BOPEND]
      ,[BLCHDT]
      ,[BDBA]
      ,[BGUAR]
      ,[BTERPC]
      ,[BTERDA]
      ,[BTERCD]
      ,[BBO]
      ,[BCRMGR]
      ,[BHOLDQ]
      ,[BHOLD]
      ,[BHCHG]
      ,[BOV120]
      ,[BCOUNT]
      ,[BWHERE]
      ,[BLANGU]
      ,[BSPCLP]
      ,[BPOWRK]
      ,[BBRAN#] as BBRAN
      ,[BINVWK]
      ,[BORDER]
      ,[BTRRT1]
      ,[BTRRT2]
      ,[BTRRT3]
      ,[BPRVBA]
      ,[BSLAST]
      ,[BS2YAG]
      ,[BBNK#1]
      ,[BBANK1]
      ,[FILLER]
      ,[BMSGCD]
      ,[BAR#] as BAR
      ,[BML]
      ,[BINT$] as BINT
      ,[BBNK#2] as BBNK2
      ,[BBANK2]
      ,[FILL1]
      ,[BSHIP#] as BSHIP
      ,[BWARE#] as BWARE
      ,[BCHAIN]
      ,[BINTPC]
      ,[FILL2]
      ,[BSS#] as BSS
      ,[BSTHIS]
      ,[BOPENA]
      ,[BOV15]
      ,[BOV30]
      ,[BOV45]
      ,[BOV60]
      ,[BOV90]
      ,[BMINYN]
      ,[BDELYN]
      ,[BOPENP]
      ,[BCLIMI]
      ,[BBALFW]
      ,[BBCOCD]
      ,[BCLAS2]
      ,[BCOPIE]
      ,[BCOMM1]
      ,[BCOMM2]
      ,[BLPAYD]
      ,[BLSALD]
      ,[BCLAS3]
      ,[BTAXST]
      ,[BTAXOT]
      ,[BFILL3]
      ,[BPREF]
      ,[BDEL]
    from dancik_wan.billto
)
    select * from CombinedData
